# Generated by Django 5.0.4 on 2024-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('DateOfJoin', models.DateField()),
                ('Img', models.CharField(max_length=100)),
            ],
        ),
    ]
